const LOADER_PUSH = 'LOADER_PUSH',
    LOADER_POP = 'LOADER_POP',
    LOADER_CLEAR = 'LOADER_CLEAR',
    REQUEST_INIT = 'REQUEST_INIT',
    REQUEST_SUCCESS = 'REQUEST_SUCCESS',
    REQUEST_FAILURE = 'REQUEST_FAILURE';

export {
    LOADER_PUSH,
    LOADER_POP,
    LOADER_CLEAR,
    REQUEST_INIT,
    REQUEST_FAILURE,
    REQUEST_SUCCESS
};